In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
x = np.array([10, 20, 30, 40, 50])
x

array([10, 20, 30, 40, 50])

In [22]:
x = np.arange(0, 100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
x = np.random.normal(10, 5, 1000)
x

array([ 9.67842381, 11.0387649 , 21.26510502,  1.12490277, 11.17270071,
        9.13265705, 12.70142641, 11.59035389, 11.14026935, 10.49948209,
       22.2301594 ,  7.10983268,  7.99298939, 11.47294996,  7.5864319 ,
       11.36418581,  4.61670688, 16.82726529,  8.06193992,  5.06999575,
        5.51613473, 10.32773592,  7.84970535,  6.49934969, 10.95040616,
        9.7852157 ,  6.71423081, 15.4096264 ,  3.29431354,  3.45460617,
        6.6833369 , 12.33359012,  8.12280571, 15.87834703, 11.51862983,
        7.17026758,  6.74966687, 10.6953241 , 16.62209787,  7.97920234,
        9.82825737,  5.44174979,  6.55538905,  4.40632683, 10.04207965,
       14.37065373,  3.9713933 , 12.3517861 ,  6.12380793, 15.34422157,
        6.46017865, 12.98293486, 11.32054164,  5.36551224,  0.89587652,
       15.77346687, 12.39191142,  8.16641551,  6.27807672,  2.83106256,
       16.5686468 ,  4.00461128,  7.58826372,  9.4162465 , 12.32283761,
       11.68795813,  3.87320556,  8.95146801, 16.23333329, 11.12

In [25]:
print(f"Media: {x.mean()}")
print(f"Desviación: {x.std()}")
print(f"Varianza: {x.var()}")
print(f"Mediana: {np.median(x)}")


Media: 10.010033493714626
Desviación: 4.987961106132941
Varianza: 24.879755996294953
Mediana: 10.077437030232602


In [26]:
x = np.arange(10, 110, 10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
x.reshape(2, 5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [19]:
x.reshape(5, 2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [28]:
x.reshape(10,1)

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [36]:
x + 6

array([ 16,  26,  36,  46,  56,  66,  76,  86,  96, 106])

In [37]:
6 + x - 6

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [52]:
from time import time
b0 = 5
b1 = 2

x = np.arange(1, 10000000)

y = np.empty_like(x)
y


array([0, 0, 0, ..., 0, 0, 0])

In [55]:
start = time()
for index, value in enumerate(x):
    y[index] = b0 + b1 * value
end = time()

print(f"Elapsed time: {end - start}")
y


Elapsed time: 5.18686318397522


array([       7,        9,       11, ..., 19999999, 20000001, 20000003])

In [54]:
start = time()
y = b0 + b1 * x
end = time()

print(f"Elapsed time: {end - start}")
y

Elapsed time: 0.061421871185302734


array([       7,        9,       11, ..., 19999999, 20000001, 20000003])

### Solución con NumPy

In [59]:
vect1 = np.ones_like(x).reshape(-1, 1)
x = np.reshape(x, (-1, 1))
A = np.hstack([x, vect1])
betas = np.array([b1, b0])

start = time()
y1 = np.matmul(A, betas)
end = time()
print(f"Elapsed time: {end - start}")
y1

Elapsed time: 0.059396982192993164


array([       7,        9,       11, ..., 19999999, 20000001, 20000003])

In [60]:
x = np.reshape(x, (-1, 1))
vect1 = np.ones_like(x)
A = np.hstack([x, vect1])
betas = np.array([b1, b0])

start = time()
y1 = np.matmul(A, betas)
end = time()
print(f"Elapsed time: {end - start}")
y1

Elapsed time: 0.05163097381591797


array([       7,        9,       11, ..., 19999999, 20000001, 20000003])

### Pandas

In [62]:
x = np.random.rand(10)
x

array([0.87165072, 0.20207679, 0.63820255, 0.7730413 , 0.03624187,
       0.9221263 , 0.99489263, 0.42255819, 0.14560699, 0.6870452 ])

In [65]:
pd.Series(x) # explicit indexes

0    0.871651
1    0.202077
2    0.638203
3    0.773041
4    0.036242
5    0.922126
6    0.994893
7    0.422558
8    0.145607
9    0.687045
dtype: float64

In [67]:
pd.Series(x, index = np.array(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"])) # explicit indexes


Jan    0.871651
Feb    0.202077
Mar    0.638203
Apr    0.773041
May    0.036242
Jun    0.922126
Jul    0.994893
Aug    0.422558
Sep    0.145607
Oct    0.687045
dtype: float64

In [71]:
sells_month = { "Jan": 100, "Feb": 200, "Mar": 300, "Apr": 400, "May": 500, "Jun": 600, "Jul": 700, "Aug": 800, "Sep": 900, "Oct": 1000 }
sells = pd.Series(sells_month) # implicit indexes

In [76]:
sells[0]

100

In [77]:
sells["Jan"]

100

In [79]:
list(sells.index)

['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct']

In [80]:
list(sells.values)

[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

#### Dataframes

In [88]:
data = {
    "ColA": pd.Series([10, 20, 30, 40, 50]),
    "ColB": pd.Series([100, 200, 300, 400, 500]),
    "ColC": pd.Series(["A", "B", "C", "D", "E"])
}

df = pd.DataFrame(data)
df


ColA  ColB ColC
0    10   100    A
1    20   200    B
2    30   300    C
3    40   400    D
4    50   500    E

In [90]:
df["ColA"]

0    10
1    20
2    30
3    40
4    50
Name: ColA, dtype: int64

In [92]:
type(df["ColA"])

pandas.core.series.Series

In [95]:
df[["ColB", "ColA", "ColC"]]

ColB  ColA ColC
0   100    10    A
1   200    20    B
2   300    30    C
3   400    40    D
4   500    50    E

In [98]:
df.loc[0, "ColC"]

'A'

In [99]:
df.loc[: , "ColC"]

0    A
1    B
2    C
3    D
4    E
Name: ColC, dtype: object

In [101]:
df.iloc[0, 2 ] # i stands for index

'A'

In [104]:
df.loc[[3,0], ["ColA", "ColC"]]

ColA ColC
3    40    D
0    10    A

#### Filtros

In [105]:
df3 = pd.DataFrame(
    {
        'A': np.random.randint(1, 21, 10),
        'B': np.random.randint(1, 21, 10),
        'Et': np.array([True, True, True, False, False, False, True, False, True, False])
    },
    index=np.arange(1, 11, 1)
)
df3


A   B     Et
1   18  15   True
2   11   4   True
3   15   4   True
4    9   6  False
5    6   8  False
6    2   1  False
7   15  16   True
8    5  14  False
9   10   8   True
10   3  19  False

In [106]:
df3[df3["A"] > 10]

A   B    Et
1  18  15  True
2  11   4  True
3  15   4  True
7  15  16  True

In [107]:
df3[(df3["A"] > 10 ) & (df3["B"] < 5)]

A  B    Et
2  11  4  True
3  15  4  True

In [108]:
df3[(df3["A"] < 5 ) | (df3["B"] > 10)]

A   B     Et
1   18  15   True
6    2   1  False
7   15  16   True
8    5  14  False
10   3  19  False

In [109]:
df3[(df3["Et"] == False )]

A   B     Et
4   9   6  False
5   6   8  False
6   2   1  False
8   5  14  False
10  3  19  False

In [116]:
df3[(df3["Et"] == False ) & (df3["A"] > 5)].loc[:, ["A"]]

A
4  9
5  6

In [117]:
df3.columns.values

array(['A', 'B', 'Et'], dtype=object)

In [118]:
df3.index.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Aggregations 

In [119]:
df3["A"].sum()

94

In [120]:
df3["A"].mean()

9.4

In [121]:
df3.sum()

A     94
B     95
Et     5
dtype: int64

In [126]:
df3

A   B     Et
1   18  15   True
2   11   4   True
3   15   4   True
4    9   6  False
5    6   8  False
6    2   1  False
7   15  16   True
8    5  14  False
9   10   8   True
10   3  19  False

In [127]:
df3.sum(axis=1)


1     34.0
2     16.0
3     20.0
4     15.0
5     14.0
6      3.0
7     32.0
8     19.0
9     19.0
10    22.0
dtype: float64

In [125]:
df3.mean(axis=1)

1     11.333333
2      5.333333
3      6.666667
4      5.000000
5      4.666667
6      1.000000
7     10.666667
8      6.333333
9      6.333333
10     7.333333
dtype: float64

In [128]:
df3["Et"].value_counts()

True     5
False    5
Name: Et, dtype: int64

In [130]:
df3.sort_values(by="A", ascending=False)

A   B     Et
1   18  15   True
3   15   4   True
7   15  16   True
2   11   4   True
9   10   8   True
4    9   6  False
5    6   8  False
8    5  14  False
10   3  19  False
6    2   1  False

### Group by

In [134]:
df3.groupby("Et").sum()

A   B
Et           
False  25  48
True   69  47

In [138]:
df3.groupby("Et", group_keys=False).mean()

A    B
Et              
False   5.0  9.6
True   13.8  9.4

In [139]:
df3.groupby("Et").agg({"A": "sum", "B": "mean"})

A    B
Et            
False  25  9.6
True   69  9.4

In [140]:
df3.groupby("Et").B.aggregate(["sum", "mean"])

sum  mean
Et              
False   48   9.6
True    47   9.4

#### CSV

In [147]:
dataset = pd.read_csv("hotel_bookings.csv")
dataset.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03  

[5 rows x 32 columns]

In [149]:
dataset.shape

(119390, 32)

In [151]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [152]:
dataset.columns.values

array(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'], dtype=object)

In [157]:
## unique countries

dataset["country"].unique()

array(['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', nan, 'ROU', 'NOR', 'OMN',
       'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
       'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
       'BWA', 'LUX', 'SVN', 'ALB', 'IND', 'CHN', 'MEX', 'MAR', 'UKR',
       'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
       'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
       'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
       'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
       'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
       'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
       'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'E